const supabase=require('../config/supabase');
async function getEbooks(req,res,next){try{const {data,error}=await supabase.from('ebooks').select('*').eq('is_published',true).order('is_featured',{ascending:false}).order('created_at',{ascending:false});if(error)throw error;const ebooks=(data||[]).map(e=>({...e,coverImage:supabase.storage.from('ebook-covers').getPublicUrl(e.cover_path).data.publicUrl}));res.json({success:true,ebooks});}catch(e){next(e);}}
async function getEbookById(req,res,next){try{const {data,error}=await supabase.from('ebooks').select('*').eq('id',req.params.id).eq('is_published',true).single();if(error||!data)return res.status(404).json({success:false,message:'E-book not found'});data.coverImage=supabase.storage.from('ebook-covers').getPublicUrl(data.cover_path).data.publicUrl;res.json({success:true,ebook:data});}catch(e){next(e);}}
function validateEbook(input){const required=['title','slug','description','cover_path','file_path'];for(const field of required){if(!input[field]||typeof input[field]!=='string')throw new Error(`${field} is required`);}if(!Number.isFinite(Number(input.price))||Number(input.price)<0)throw new Error('price must be a non-negative number');}
function ebookPayload(input){const allowed=['title','slug','description','author','price','currency','cover_path','file_path','preview_path','pages','category','tags','is_published','is_featured'];return Object.fromEntries(Object.entries(input).filter(([key])=>allowed.includes(key)));}
async function createEbook(req,res,next){try{validateEbook(req.body);const {data,error}=await supabase.from('ebooks').insert(ebookPayload(req.body)).select().single();if(error)throw error;res.status(201).json({success:true,ebook:data});}catch(e){next(e);}}
async function listAdminEbooks(req,res,next){try{const {data,error}=await supabase.from('ebooks').select('*').order('created_at',{ascending:false});if(error)throw error;res.json({success:true,ebooks:data||[]});}catch(e){next(e);}}
async function updateEbook(req,res,next){try{const payload=ebookPayload(req.body);if(!Object.keys(payload).length)return res.status(400).json({success:false,message:'No editable fields supplied'});if(payload.price!==undefined&&(!Number.isFinite(Number(payload.price))||Number(payload.price)<0))return res.status(400).json({success:false,message:'price must be a non-negative number'});const {data,error}=await supabase.from('ebooks').update(payload).eq('id',req.params.id).select().single();if(error)throw error;res.json({success:true,ebook:data});}catch(e){next(e);}}
async function createUploadUrl(req,res,next){try{const {bucket,path}=req.body||{};const allowed=new Set(['ebook-covers','ebook-files','ebook-previews']);if(!allowed.has(bucket)||typeof path!=='string'||!path.match(/^[a-zA-Z0-9][a-zA-Z0-9/_\-.]{0,240}$/)||path.includes('..'))return res.status(400).json({success:false,message:'Invalid upload target'});const {data,error}=await supabase.storage.from(bucket).createSignedUploadUrl(path);if(error)throw error;res.json({success:true,token:data.token,path:data.path});}catch(e){next(e);}}
module.exports={getEbooks,getEbookById,createEbook,listAdminEbooks,updateEbook,createUploadUrl};
