const crypto = require("crypto");
const supabase = require("../config/supabase");
const razorpay = require("../services/razorpayService");
const { sendPurchaseEmail } = require("../services/emailService");

const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const phonePattern = /^\+?[0-9()\-\s]{7,20}$/;
const expirySeconds = () => Math.min(Math.max(Number(process.env.DOWNLOAD_EXPIRY_SECONDS || 86400), 300), 604800);
const downloadLimit = () => Math.min(Math.max(Number(process.env.DOWNLOAD_LIMIT || 3), 1), 10);

function signatureIsValid(orderId, paymentId, signature) { const expected = crypto.createHmac("sha256", process.env.RAZORPAY_KEY_SECRET).update(`${orderId}|${paymentId}`).digest("hex"); return Boolean(signature) && expected.length === signature.length && crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(signature)); }
function webhookIsValid(raw, signature) { const expected = crypto.createHmac("sha256", process.env.RAZORPAY_WEBHOOK_SECRET || "").update(raw).digest("hex"); return Boolean(signature) && expected.length === signature.length && crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(signature)); }

async function createRazorpayOrder(req, res, next) { try {
  const { ebookId, firstName, lastName, email, phone } = req.body || {};
  const first = String(firstName || "").trim(), last = String(lastName || "").trim(), customerEmail = String(email || "").trim().toLowerCase(), customerPhone = String(phone || "").trim();
  if (!ebookId || !first || !last || !emailPattern.test(customerEmail) || !phonePattern.test(customerPhone)) return res.status(400).json({ success: false, message: "First name, last name, valid email, and valid phone number are required." });
  const { data: ebook, error } = await supabase.from("ebooks").select("*").eq("id", ebookId).eq("is_published", true).single();
  if (error || !ebook) return res.status(404).json({ success: false, message: "E-book not found." });
  const amount = Math.round(Number(ebook.price) * 100); if (!Number.isInteger(amount) || amount <= 0) return res.status(400).json({ success: false, message: "Invalid e-book price." });
  const order = await razorpay.orders.create({ amount, currency: ebook.currency || "INR", receipt: `ebook_${Date.now()}_${crypto.randomBytes(4).toString("hex")}`.slice(0, 40), notes: { ebookId: ebook.id, firstName: first, lastName: last, customerEmail, customerPhone } });
  const { data: transaction, error: transactionError } = await supabase.from("transactions").insert({ ebook_id: ebook.id, customer_name: `${first} ${last}`, customer_first_name: first, customer_last_name: last, customer_phone: customerPhone, customer_email: customerEmail, razorpay_order_id: order.id, amount_paise: amount, currency: order.currency, status: "created" }).select().single();
  if (transactionError) throw transactionError;
  res.json({ success: true, keyId: process.env.RAZORPAY_KEY_ID, orderId: order.id, amount: order.amount, currency: order.currency, transactionId: transaction.id, ebook: { id: ebook.id, title: ebook.title } });
} catch (error) { next(error); } }

async function createDelivery(transaction, ebook) { const { data: existing, error: existingError } = await supabase.from("downloads").select("*").eq("transaction_id", transaction.id).maybeSingle(); if (existingError) throw existingError; const seconds = expirySeconds(), expiresAt = existing?.expires_at || new Date(Date.now() + seconds * 1000).toISOString(); const download = existing || (await supabase.from("downloads").insert({ transaction_id: transaction.id, ebook_id: ebook.id, user_id: transaction.user_id || null, expires_at: expiresAt, download_count: 0, download_limit: downloadLimit() }).select().single()).data; if (!download) throw new Error("Unable to create ebook delivery."); const baseUrl = process.env.PUBLIC_API_URL || "http://localhost:5000"; return { url: `${baseUrl}/api/payment/download/${download.id}`, expiresAt }; }
async function sendDelivery(transaction, ebook) { const download = await createDelivery(transaction, ebook); if (transaction.delivery_email_sent_at) return { emailSent: true, download }; try { const sent = await sendPurchaseEmail({ transaction, ebook, download }); if (sent.skipped) return { emailSent: false, download }; await supabase.from("transactions").update({ delivery_email_sent_at: new Date().toISOString(), delivery_email_error: null }).eq("id", transaction.id); return { emailSent: true, download }; } catch (error) { console.error("Purchase email failed:", error.message); await supabase.from("transactions").update({ delivery_email_error: error.message }).eq("id", transaction.id); return { emailSent: false, download }; } }
async function captureOrder({ orderId, paymentId, signature }) { if (!signatureIsValid(orderId, paymentId, signature)) throw Object.assign(new Error("Invalid Razorpay payment signature."), { status: 400 }); const { data: transaction, error } = await supabase.from("transactions").select("*,ebooks(*)").eq("razorpay_order_id", orderId).single(); if (error || !transaction?.ebooks) throw Object.assign(new Error("Transaction not found."), { status: 404 }); const payment = await razorpay.payments.fetch(paymentId); if (payment.order_id !== orderId || Number(payment.amount) !== Number(transaction.amount_paise) || payment.status !== "captured") throw Object.assign(new Error("Payment is not captured yet."), { status: 409 }); if (transaction.razorpay_payment_id && transaction.razorpay_payment_id !== paymentId) throw Object.assign(new Error("Another payment is already recorded for this order."), { status: 409 }); const { data: captured, error: updateError } = await supabase.from("transactions").update({ razorpay_payment_id: paymentId, razorpay_signature: signature, payment_method: payment.method || null, payment_date: new Date(Number(payment.created_at) * 1000).toISOString(), status: "captured", webhook_received: transaction.webhook_received || false }).eq("id", transaction.id).select("*,ebooks(*)").single(); if (updateError) throw updateError; return { transaction: captured, ...(await sendDelivery(captured, captured.ebooks)) }; }

async function verifyRazorpayPayment(req, res, next) { try { const { razorpayPaymentId, razorpayOrderId, razorpaySignature } = req.body || {}; if (!razorpayPaymentId || !razorpayOrderId || !razorpaySignature) return res.status(400).json({ success: false, message: "Incomplete Razorpay payment details." }); const result = await captureOrder({ orderId: razorpayOrderId, paymentId: razorpayPaymentId, signature: razorpaySignature }); res.json({ success: true, message: result.emailSent ? "Payment successful. Your ebook is ready and a backup link was emailed." : "Payment successful. Your ebook is ready. Download it now; email delivery will be enabled after the sender domain is verified.", transactionId: result.transaction.id, download: result.download }); } catch (error) { next(error); } }
async function razorpayWebhook(req, res, next) { try { const raw = Buffer.isBuffer(req.body) ? req.body : Buffer.from(req.body || ""); const signature = req.headers["x-razorpay-signature"]; if (!webhookIsValid(raw, signature)) return res.status(400).json({ success: false, message: "Invalid webhook signature." }); const event = JSON.parse(raw.toString("utf8")); const payment = event.payload?.payment?.entity; if (event.event === "payment.captured" && payment?.order_id && payment?.id) { const { data: transaction } = await supabase.from("transactions").select("*").eq("razorpay_order_id", payment.order_id).maybeSingle(); if (transaction) { await supabase.from("transactions").update({ razorpay_payment_id: payment.id, payment_method: payment.method || null, payment_date: new Date(Number(payment.created_at) * 1000).toISOString(), status: "captured", webhook_received: true }).eq("id", transaction.id); const { data: captured } = await supabase.from("transactions").select("*,ebooks(*)").eq("id", transaction.id).single(); if (captured?.ebooks && !captured.delivery_email_sent_at) await sendDelivery(captured, captured.ebooks); } } res.json({ success: true }); } catch (error) { next(error); } }
async function downloadEbook(req, res, next) { try { const { data: download, error } = await supabase.from("downloads").select("*,ebooks(*)").eq("id", req.params.downloadId).single(); if (error || !download?.ebooks) return res.status(404).send("Download link not found."); if (new Date(download.expires_at) <= new Date()) return res.status(410).send("This download link has expired."); const { data: claimed, error: claimError } = await supabase.from("downloads").update({ download_count: Number(download.download_count) + 1 }).eq("id", download.id).lt("download_count", Number(download.download_limit)).select().maybeSingle(); if (claimError) throw claimError; if (!claimed) return res.status(403).send("Download limit reached."); const seconds = Math.max(60, Math.floor((new Date(download.expires_at).getTime() - Date.now()) / 1000)); const { data: signed, error: signedError } = await supabase.storage.from("ebook-files").createSignedUrl(download.ebooks.file_path, seconds); if (signedError || !signed?.signedUrl) throw signedError || new Error("Unable to prepare ebook."); res.setHeader("Cache-Control", "no-store"); res.redirect(302, signed.signedUrl); } catch (error) { next(error); } }
async function getPurchases(req, res, next) { try { const { data, error } = await supabase.from("transactions").select("*,ebooks(*)").eq("user_id", req.user.id).eq("status", "captured").order("created_at", { ascending: false }); if (error) throw error; res.json({ success: true, purchases: data || [] }); } catch (error) { next(error); } }
module.exports = { createRazorpayOrder, verifyRazorpayPayment, razorpayWebhook, downloadEbook, getPurchases };
