"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { supabase } from "../../lib/supabase";
import { getPurchases } from "../../lib/api";

export default function AccountPage() {
  const [user, setUser] = useState(null); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [notice, setNotice] = useState(""); const [purchases, setPurchases] = useState([]);
  async function load() { const { data } = await supabase.auth.getUser(); setUser(data.user || null); if (data.user) { try { setPurchases((await getPurchases()).purchases); } catch (e) { setNotice(e.message); } } }
  useEffect(() => { load(); const { data: listener } = supabase.auth.onAuthStateChange(() => load()); return () => listener.subscription.unsubscribe(); }, []);
  async function submit(e) { e.preventDefault(); setNotice(""); const { error } = user ? await supabase.auth.signOut() : await supabase.auth.signInWithPassword({ email, password }); if (error) setNotice(error.message); }
  async function signUp() { setNotice(""); const { error } = await supabase.auth.signUp({ email, password }); setNotice(error ? error.message : "Check your email to confirm your account, then sign in."); }
  return <main className="min-h-screen bg-[#020304] px-6 py-28 text-white"><div className="mx-auto max-w-3xl"><Link href="/" className="text-sm text-blue-400">← Back to portfolio</Link><h1 className="mt-8 text-4xl font-black">Your library</h1>{!user ? <form onSubmit={submit} className="mt-8 max-w-md rounded-3xl border border-white/10 bg-white/[.03] p-6"><p className="text-white/60">Sign in to keep and re-download your purchases.</p><input required type="email" className="mt-5 w-full rounded-xl bg-white/5 p-3" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} /><input required minLength="6" type="password" className="mt-3 w-full rounded-xl bg-white/5 p-3" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} /><button className="mt-5 w-full rounded-xl bg-white p-3 font-semibold text-black">Sign in</button><button type="button" onClick={signUp} className="mt-3 w-full text-sm text-blue-400">Create an account</button>{notice&&<p className="mt-4 text-sm text-white/60">{notice}</p>}</form> : <><div className="mt-5 flex items-center justify-between rounded-2xl border border-white/10 p-5"><p>{user.email}</p><button onClick={submit} className="text-sm text-blue-400">Sign out</button></div><div className="mt-8 space-y-4">{purchases.length ? purchases.map(p=><article key={p.id} className="flex items-center gap-4 rounded-2xl border border-white/10 p-4"><div className="h-16 w-12 overflow-hidden rounded bg-white/5">{p.ebook.coverImage&&<img src={p.ebook.coverImage} alt="" className="h-full w-full object-cover"/>}</div><div className="flex-1"><h2 className="font-bold">{p.ebook.title}</h2><p className="text-sm text-white/50">Purchased {new Date(p.purchasedAt).toLocaleDateString()}</p></div><a href={p.download.url} className="rounded-lg bg-white px-4 py-2 text-sm font-semibold text-black">Download</a></article>) : <p className="text-white/50">No account-linked purchases yet.</p>}</div></>}</div></main>;
}
